spring:
  application:
    name: Small-Bank-WAS
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/sb_db
    username: sb_db
    password: smallback1234!
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 1e0483c1d51e06ddc4ce2892d91eea03
            client-secret: IJLdgWf2OirmqjALGdAPIETngQDetIce
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
            authorization-grant-type: authorization_code #고정 값
            redirect-uri: https://sppd.kro.kr/login/oauth2/code/kakao #redirect-uri
            client-authentication-method: client_secret_post
          google:
            client-id: 557305737448-cp4ojl64753kk9tgqv6ldgacj0f4fu0j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://sppd.kro.kr/login/oauth2/code/google
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update #create validate update

logging:
  config: classpath:logback-spring.xml

server:
  port: 443
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-password: sb1234!
    key-store-type: PKCS12
#SSL free 발급
#https://manage.sslforfree.com/certificates
#자동 갱신
#https://certbot.eff.org/instructions?ws=apache&os=windows
# (command) openssl pkcs12 -export -out keystore.p12 -inkey private.key -in certificate.crt

sppd:
  schedule:
    weather: '0 30 2/3 * * ?'
  homeDir: ${user.dir}
  logDir: ${sppd.homeDir}/log
  logFileName: SppdWas
  data:
    weather:
      # 성남동
      nx: 63
      ny: 124
    bus:
      # 종합 운동장 사거리
      stationIds: 205000136, 204000055
    serviceKey: 9G4mXvJnJcvcO5RL3kH8WZhCiyCDl00AeqxkvWBoZydbNBK4K%2FBWd1iZcmoI3AYdCu%2B%2BbMpkdrNr%2F5LG8SdPhA%3D%3D

# 종합 운동장 사거리 bus mapping {routedId: busNum}
data:
  routedBusMap:
#   종합운동장 사거리
    204000020: 33
    204000076: 382
    241221002: 8
#   수성교
    204000005: 57
    204000021: 51
    204000026: 52
    204000040: 340
    204000084: 331
    204000159: 342
    227000003: 30
    234000095: 9
    234000012: 17
    234000849: 17-1
    234001578: 17-1A
    241213002: 88-1
  stationIdMap:
    204000055: 수성교.소방서
    205000136: 종합운동장사거리
