logging:
  level:
    com:
      dev: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://172.22.112.1:15432/sb_db

server:
  servlet:
    session:
      timeout: 86400
      maximum-sessions: 1
      max-sessions-prevents-login: false 